### PR TITLE
extension: make compatible with libnm

### PR DESCRIPTION
**Pull request by lkundrak**
libnm-glib has been deprecated in favor of libnm for ages. GNOME Shell
seems to be among the last bits to be ported. This is now being done [1]:

[1] https://bugzilla.gnome.org/show_bug.cgi?id=789811

Unfortunately, due to GLib limitations, libnm-glib.so and libnm.so can't
be loaded at the same time and the attempt to do so results in a nasty
crash. The extensions thus needs to be updated to libnm.

### CODE REVIEW

**Comment by kgshank** [comment]
Thanks @lkundrak

**Comment by mbiebl** [comment]
I tried the latest version, including this patch and got this (with a libnm based gnome-shell):
```
Nov 07 16:48:38 pluto gnome-shell[26707]: JS ERROR: Exception in callback for signal: activate: Error: Expected type interface for Argument 'connection' but got type 'string'
                                          WifiDisconnector<._reconnect@/usr/share/gnome-shell/extensions/disconnect-wifi@kgshank.net/extension.js:154:17
                                          wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
                                          WifiDisconnector<._addAllMenus/wrapper.reconnectItem<@/usr/share/gnome-shell/extensions/disconnect-wifi@kgshank.net/extension.js:130:33
                                          PopupMenuBase<.addAction/<@resource:///org/gnome/shell/ui/popupMenu.js:480:13
                                          _emit@resource:///org/gnome/gjs/modules/signals.js:126:27
                                          PopupBaseMenuItem<.activate@resource:///org/gnome/shell/ui/popupMenu.js:166:9
                                          wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
                                          PopupBaseMenuItem<._onButtonReleaseEvent@resource:///org/gnome/shell/ui/popupMenu.js:127:9
                                          wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
```

**Comment by mbiebl** [comment]
With a  libnm-glib based gnome-shell, the extension still works fine.

The problem happens when trying to reconnect

**Comment by lkundrak** [comment]
@mbiebl I think it's been broken by the second hunk of 1e15074bafdee7a20db57b78143d50d1793946f1. Fix in #13

**Pull request merged**
